### ISSUE TITLE
Initialize and integrate Cloud Firestore into our app

### ISSUE THREAD

**Issue by lausan3** [GomikoApp/Gomiko#13]
**TASKS:**
- [x] Initialize Cloud Firestore
- [x] Integrate it into our user creation system
- [ ] Migrate user data from Firebase Auth to Firestore

**Comment by lausan3** [comment]
[Database Design Diagram](https://lucid.app/lucidchart/3e40d3e6-c9d1-44c2-ae10-3c664f166536/edit?invitationId=inv_2c4bbb04-7484-4f72-b98b-422aea26ecb2)

**Comment by lausan3** [comment]
Users are now being sent to Cloud Firestore whenever they create an account or sign in with oauth.

![GomikoUserInFirestore](https://github.com/GomikoApp/Gomiko/assets/92795688/8bfac5e0-48d1-4665-a721-0a8318032eb1)
