### ISSUE TITLE
Finish up the design of the Signup/Login page sequence

### ISSUE THREAD

**Issue by lausan3** [GomikoApp/Gomiko#14]
**TASKS:**
- [x] Getting Started Page
- [x] Sign up Page
- [x] Login Page
- [x] Forgot password Page
- [ ] Enter verification code Page
- [ ] Change password Page

**Comment by SLuo490** [comment]
Might need to remove change password page to future development when we get the profile screen working. As for the verification code, we need to have an option to sign in/create account with phone.
